name: Deploy to HubSpot

on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: HubSpot Deploy Action
        uses: HubSpot/hubspot-cms-deploy-action@v2.0.1
        with:
          src_dir: .
          dest_dir: NewPortfolio
          account_id: ${{ vars.accountId }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}
